Switch back to previous debug configure code from XDT_FEATURE_DEBUG().
I'd like to see if this has an impact on make distcheck. It could be
that only modules using XDT_FEATURE_DEBUG(), like xfconf and Thunar,
break due to this error in the scanner code generated by gtk-doc:

thunarx-scan.c: In function ‘describe_signed_constant’:
thunarx-scan.c:884: error: comparison between signed and unsigned